{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.1554.0 (23.12)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Territory Lookup\",\"Product Lookup\",\"Product Categories Lookup\",\"Product Subcategories Lookup\",\"Customer Lookup\",\"Largest Asset Management Firms\",\"Calendar Lookup\",\"Rolling Calendar\",\"Product Category Sales (Unpivot Demo)\",\"Sales Data\",\"Sample File\",\"Parameter1\",\"Transform Sample File\",\"Transform File\",\"Returns Data\",\"Measure Table\",\"Path\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\",\"DaxQueryView_Desktop\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Largest Asset Management Firms",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Web.BrowserContents(\"https://en.wikipedia.org/wiki/List_of_asset_management_firms\"),\r",
          "    #\"Extracted Table From Html\" = Html.Table(Source, {{\"Column1\", \"TABLE.sortable.wikitable > * > TR > :nth-child(1)\"}, {\"Column2\", \"TABLE.sortable.wikitable > * > TR > :nth-child(2)\"}, {\"Column3\", \"TABLE.sortable.wikitable > * > TR > :nth-child(3)\"}, {\"Column4\", \"TABLE.sortable.wikitable > * > TR > :nth-child(4)\"}}, [RowSelector=\"TABLE.sortable.wikitable > * > TR\"]),\r",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Extracted Table From Html\", [PromoteAllScalars=true]),\r",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Rank\", Int64.Type}, {\"Firm/company\", type text}, {\"Country\", type text}, {\"AUM (billion USD)\", type number}}),\r",
          "    #\"Changed To Currency\" = Table.TransformColumnTypes(#\"Changed Type\",{{\"AUM (billion USD)\", Currency.Type}})\r",
          "in\r",
          "    #\"Changed To Currency\""
        ],
        "kind": "m",
        "lineageTag": "d05605e3-3f77-414b-aa8e-9f42bd8ec0b2",
        "queryGroup": "Demo Queries"
      },
      {
        "name": "Product Category Sales (Unpivot Demo)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(Path&\"\\Product Category Sales (Unpivot Demo).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Date\", type date}, {\"Product Category\", type text}, {\"North Region\", Int64.Type}, {\"Central Region\", Int64.Type}, {\"South Region\", Int64.Type}}),",
          "    #\"Unpivoted Only Selected Columns\" = Table.Unpivot(#\"Changed Type\", {\"North Region\", \"Central Region\", \"South Region\"}, \"Attribute\", \"Value\"),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Unpivoted Only Selected Columns\",{{\"Attribute\", \"Region\"}, {\"Value\", \"Quantity Sold\"}}),",
          "    #\"Pivoted Column\" = Table.Pivot(#\"Renamed Columns\", List.Distinct(#\"Renamed Columns\"[Region]), \"Region\", \"Quantity Sold\", List.Sum)",
          "in",
          "    #\"Pivoted Column\""
        ],
        "kind": "m",
        "lineageTag": "751dcd2d-ebdb-4d31-a79d-8d8edf40b6da",
        "queryGroup": "Demo Queries"
      },
      {
        "name": "Sample File",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Source = Folder.Files(Path&\"\\Sales Data\"),",
          "    Navigation1 = Source{0}[Content]",
          "in",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "bdea8828-6bb3-4651-9358-499e3ad97ed4",
        "queryGroup": "Transform File from Sales Data\\Helper Queries"
      },
      {
        "name": "Parameter1",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "62af8244-cae0-4d69-8484-e6427911b4b8",
        "queryGroup": "Transform File from Sales Data\\Helper Queries"
      },
      {
        "name": "Transform Sample File",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Csv.Document(Parameter1,[Delimiter=\",\", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),\r",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])\r",
          "in\r",
          "    #\"Promoted Headers\""
        ],
        "kind": "m",
        "lineageTag": "f18e5a44-ec5b-4b7e-a088-4bbb381103e7",
        "queryGroup": "Transform File from Sales Data"
      },
      {
        "name": "Transform File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter1 as binary) => let",
          "        Source = Csv.Document(Parameter1,[Delimiter=\",\", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "        #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "    in",
          "        #\"Promoted Headers\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "d6f25cc5-50a7-4886-95d1-08e851490eb8",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transform Sample File\"\"}\" ]",
        "queryGroup": "Transform File from Sales Data\\Helper Queries"
      },
      {
        "name": "Rolling Calendar",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = #date(2022,1,1),\r",
          "    Custom1 = List.Dates(\r",
          "    Source,\r",
          "    Number.From(DateTime.LocalNow()) - Number.From(Source),\r",
          "    #duration(1,0,0,0)\r",
          "),\r",
          "    #\"Converted to Table\" = Table.FromList(Custom1, Splitter.SplitByNothing(), null, null, ExtraValues.Error),\r",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Converted to Table\",{{\"Column1\", type date}}),\r",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Column1\", \"Date\"}}),\r",
          "    #\"Inserted Year\" = Table.AddColumn(#\"Renamed Columns\", \"Year\", each Date.Year([Date]), Int64.Type),\r",
          "    #\"Inserted Start of Month\" = Table.AddColumn(#\"Inserted Year\", \"Start of Month\", each Date.StartOfMonth([Date]), type date),\r",
          "    #\"Inserted Start of Quarter\" = Table.AddColumn(#\"Inserted Start of Month\", \"Start of Quarter\", each Date.StartOfQuarter([Date]), type date)\r",
          "in\r",
          "    #\"Inserted Start of Quarter\""
        ],
        "kind": "m",
        "lineageTag": "da40a3c5-c66b-4f88-b2e8-671141b2f921"
      },
      {
        "name": "Path",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"D:\\Explore\\Datasets\\AdventureWorks Raw Data\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "c95b0d1c-9901-4b12-aeea-93f5dd3a8a0d"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Demo Queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Transform File from Sales Data"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from Sales Data\\Helper Queries"
      }
    ],
    "relationships": [
      {
        "name": "86b4188d-f349-41d2-986f-cdc686f17f35",
        "fromColumn": "CustomerKey",
        "fromTable": "Sales Data",
        "toColumn": "CustomerKey",
        "toTable": "Customer Lookup"
      },
      {
        "name": "46fc1863-fe4e-4937-b63a-e47608daab04",
        "fromColumn": "ProductKey",
        "fromTable": "Sales Data",
        "toColumn": "ProductKey",
        "toTable": "Product Lookup"
      },
      {
        "name": "bc794927-f4a2-47df-8902-9aa3b8344ec8",
        "fromColumn": "TerritoryKey",
        "fromTable": "Sales Data",
        "toColumn": "Sales Territory Key",
        "toTable": "Territory Lookup"
      },
      {
        "name": "11e6810e-7f27-4002-a674-6c6e79098a28",
        "fromColumn": "OrderDate",
        "fromTable": "Sales Data",
        "toColumn": "Date",
        "toTable": "Calendar Lookup"
      },
      {
        "name": "f53baeeb-d336-4bca-b537-20358dc04c42",
        "fromColumn": "ProductSubcategoryKey",
        "fromTable": "Product Lookup",
        "toColumn": "ProductSubcategoryKey",
        "toTable": "Product Subcategories Lookup"
      },
      {
        "name": "a39c9695-bb60-4c38-86e4-4cc2b3637fea",
        "fromColumn": "ProductCategoryKey",
        "fromTable": "Product Subcategories Lookup",
        "toColumn": "ProductCategoryKey",
        "toTable": "Product Categories Lookup"
      },
      {
        "name": "4b829b06-1cff-4a17-b77b-cf412846765d",
        "fromColumn": "StockDate",
        "fromTable": "Sales Data",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar Lookup"
      },
      {
        "name": "da828817-35d4-4a95-93e6-05133628ce70",
        "fromColumn": "ProductKey",
        "fromTable": "Returns Data",
        "toColumn": "ProductKey",
        "toTable": "Product Lookup"
      },
      {
        "name": "d624e33b-3338-492c-af50-be5e6238d93c",
        "fromColumn": "TerritoryKey",
        "fromTable": "Returns Data",
        "toColumn": "Sales Territory Key",
        "toTable": "Territory Lookup"
      },
      {
        "name": "c636d09d-5d8e-45f3-a4c8-585cc0ff5f7b",
        "fromColumn": "ReturnDate",
        "fromTable": "Returns Data",
        "toColumn": "Date",
        "toTable": "Calendar Lookup"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Territory Lookup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Sales Territory Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isKey": true,
            "lineageTag": "5940f242-c3b7-4be6-87b5-7a017e4a13e9",
            "sourceColumn": "Sales Territory Key",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9100f4e0-a269-44ea-a928-eb1f36f0bf8e",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Country",
            "dataType": "string",
            "lineageTag": "38371130-1b6f-490e-a471-34371ca03991",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Continent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Continent",
            "dataType": "string",
            "lineageTag": "891de73e-b438-410d-bd76-32e2220be914",
            "sourceColumn": "Continent",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "Territory Hierarchy",
            "levels": [
              {
                "name": "Continent",
                "column": "Continent",
                "lineageTag": "b8105bb7-7411-4fd5-b8c9-de34cf47a9a4",
                "ordinal": 0
              },
              {
                "name": "Country",
                "column": "Country",
                "lineageTag": "c50e208b-421b-4230-b105-37246fb2505f",
                "ordinal": 1
              },
              {
                "name": "Region",
                "column": "Region",
                "lineageTag": "490b2643-bf0d-4aae-8ab2-7c6a3130c825",
                "ordinal": 2
              }
            ],
            "lineageTag": "87b86ff7-86b6-4f7e-962c-86c55d86cdbf"
          }
        ],
        "lineageTag": "a87488dc-4917-45e0-b76f-40d64909d39d",
        "partitions": [
          {
            "name": "Territory Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(Path&\"\\AdventureWorks Territory Lookup.csv\"),[Delimiter=\",\", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"SalesTerritoryKey\", Int64.Type}, {\"Region\", type text}, {\"Country\", type text}, {\"Continent\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"SalesTerritoryKey\", \"Sales Territory Key\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product Lookup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isKey": true,
            "lineageTag": "8bd70e2c-62aa-43d3-b3fc-1c2d52f710f6",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductSubcategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0dfabf54-828d-4452-a562-2cc95709c77e",
            "sourceColumn": "ProductSubcategoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductSKU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "928ea64b-53f2-4be1-ab20-a8ada5196cd8",
            "sourceColumn": "ProductSKU",
            "summarizeBy": "none"
          },
          {
            "name": "ProductName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "873d5ee1-16bb-4276-94ef-232b12b94297",
            "sourceColumn": "ProductName",
            "summarizeBy": "none"
          },
          {
            "name": "ModelName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "816c58b5-fbbf-40ed-8a17-78ee7de61ce2",
            "sourceColumn": "ModelName",
            "summarizeBy": "none"
          },
          {
            "name": "ProductDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea1ddc25-af4a-4229-90a9-78fbb4427da3",
            "sourceColumn": "ProductDescription",
            "summarizeBy": "none"
          },
          {
            "name": "ProductColor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a9b0bf3-78e9-4808-8ecc-0885753c4e5d",
            "sourceColumn": "ProductColor",
            "summarizeBy": "none"
          },
          {
            "name": "ProductStyle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e4c2ed09-e35b-46b4-abbf-61a2cc83d713",
            "sourceColumn": "ProductStyle",
            "summarizeBy": "none"
          },
          {
            "name": "ProductCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "774d2f59-7d90-4b00-8001-73e88ae34f95",
            "sourceColumn": "ProductCost",
            "summarizeBy": "sum"
          },
          {
            "name": "ProductPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "10e58b5e-3b2b-4928-92a3-5f84be4ae32f",
            "sourceColumn": "ProductPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "SKU Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "49a17f81-78a2-463c-91fc-acbdb6c40d51",
            "sourceColumn": "SKU Type",
            "summarizeBy": "none"
          },
          {
            "name": "Discount Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ID\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"Rp\"#,0.00;-\"Rp\"#,0.00;\"Rp\"#,0.00",
            "lineageTag": "05e3d03a-0535-42d8-b768-82fb51df998a",
            "sourceColumn": "Discount Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Price Point",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    'Product Lookup'[ProductPrice] > 500, \"High\",",
              "    'Product Lookup'[ProductPrice] > 100, \"Mid-Range\",",
              "    \"Others\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "2d819ea4-9f93-4a1a-9346-82d4896f1fca",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "SKU Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "LEFT(",
              "    'Product Lookup'[ProductSKU],",
              "    SEARCH(",
              "        \"-\",",
              "        'Product Lookup'[ProductSKU]",
              "    )-1",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "e7c443c6-4d91-44b2-906b-49f82992d505",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "9e21aa4c-5f28-442d-bcfa-50033bcde422",
        "partitions": [
          {
            "name": "Product Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(Path&\"\\AdventureWorks Product Lookup.csv\"),[Delimiter=\",\", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ProductKey\", Int64.Type}, {\"ProductSubcategoryKey\", Int64.Type}, {\"ProductSKU\", type text}, {\"ProductName\", type text}, {\"ModelName\", type text}, {\"ProductDescription\", type text}, {\"ProductColor\", type text}, {\"ProductSize\", type text}, {\"ProductStyle\", type text}, {\"ProductCost\", type number}, {\"ProductPrice\", type number}}),",
                "    #\"Changed To Currency\" = Table.TransformColumnTypes(#\"Changed Type\",{{\"ProductCost\", Currency.Type}, {\"ProductPrice\", Currency.Type}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed To Currency\",{\"ProductSize\"}),",
                "    #\"Inserted Column SKU Type\" = Table.AddColumn(#\"Removed Columns\", \"SKU Type\", each Text.BeforeDelimiter([ProductSKU], \"-\", 1), type text),",
                "    #\"Replaced Value in Product Style\" = Table.ReplaceValue(#\"Inserted Column SKU Type\",\"0\",\"NA\",Replacer.ReplaceText,{\"ProductStyle\"}),",
                "    #\"Inserted Multiplication\" = Table.AddColumn(#\"Replaced Value in Product Style\", \"Discount Price\", each [ProductPrice] * 0.9, Currency.Type)",
                "in",
                "    #\"Inserted Multiplication\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product Categories Lookup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ProductCategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isKey": true,
            "lineageTag": "259e2948-d3bb-4be7-b4af-6d08ef6e457c",
            "sourceColumn": "ProductCategoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "CategoryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c1dd0b9d-ac31-432f-851e-161b03a0dd97",
            "sourceColumn": "CategoryName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "296f0f78-4cbc-4aa7-96d5-a1e6032169a7",
        "partitions": [
          {
            "name": "Product Categories Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(Path&\"\\AdventureWorks Product Categories Lookup.csv\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ProductCategoryKey\", Int64.Type}, {\"CategoryName\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product Subcategories Lookup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ProductSubcategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isKey": true,
            "lineageTag": "64004109-4959-4735-95c4-2f18ec71ff10",
            "sourceColumn": "ProductSubcategoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "SubcategoryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad3339fb-40cc-45f7-b87f-0100afb4adaf",
            "sourceColumn": "SubcategoryName",
            "summarizeBy": "none"
          },
          {
            "name": "ProductCategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3642be2d-1741-457e-a580-4479a8a95774",
            "sourceColumn": "ProductCategoryKey",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "80ec2dfb-8ac1-4a25-9c79-d4fdb328dc7a",
        "partitions": [
          {
            "name": "Product Subcategories Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(Path&\"\\AdventureWorks Product Subcategories Lookup.csv\"),[Delimiter=\",\", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ProductSubcategoryKey\", Int64.Type}, {\"SubcategoryName\", type text}, {\"ProductCategoryKey\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Customer Lookup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isKey": true,
            "lineageTag": "9de18993-322b-4183-af5b-e21e9469a8e6",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "Prefix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb55f52c-39da-4f08-8f3d-b846610baf2f",
            "sourceColumn": "Prefix",
            "summarizeBy": "none"
          },
          {
            "name": "FirstName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "580d4de4-3337-41d9-8259-792fd5e68845",
            "sourceColumn": "FirstName",
            "summarizeBy": "none"
          },
          {
            "name": "LastName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "011f23e0-84fa-4469-9bfc-d11f6dd3e344",
            "sourceColumn": "LastName",
            "summarizeBy": "none"
          },
          {
            "name": "BirthDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8ffc14bd-dfbb-4d59-b7e1-7710aec77521",
            "sourceColumn": "BirthDate",
            "summarizeBy": "none"
          },
          {
            "name": "MaritalStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba8df932-707d-4f4b-ba56-0319fafc5ff6",
            "sourceColumn": "MaritalStatus",
            "summarizeBy": "none"
          },
          {
            "name": "Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "81536a8c-edc4-45cd-ac6e-e9308fbbf4a3",
            "sourceColumn": "Gender",
            "summarizeBy": "none"
          },
          {
            "name": "EmailAddress",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2b0b3eb-2e2e-48b4-96c0-eee71e9f92b4",
            "sourceColumn": "EmailAddress",
            "summarizeBy": "none"
          },
          {
            "name": "AnnualIncome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ffd9158b-5831-4b19-98b5-4a08e7d89b2c",
            "sourceColumn": "AnnualIncome",
            "summarizeBy": "none"
          },
          {
            "name": "TotalChildren",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4ebb9623-03ca-45ba-ae80-1d5d91f46ec6",
            "sourceColumn": "TotalChildren",
            "summarizeBy": "none"
          },
          {
            "name": "EducationLevel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "693a7843-96ab-4f60-9107-b835b392fe91",
            "sourceColumn": "EducationLevel",
            "summarizeBy": "none"
          },
          {
            "name": "Occupation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e193460-2c3a-4b2a-93f5-f5b3dd89155f",
            "sourceColumn": "Occupation",
            "summarizeBy": "none"
          },
          {
            "name": "HomeOwner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "de0d3cd7-9c9d-44f9-943b-92ed708a8d59",
            "sourceColumn": "HomeOwner",
            "summarizeBy": "none"
          },
          {
            "name": "Full Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fa980137-1ffb-489d-8391-0455c47e0be5",
            "sourceColumn": "Full Name",
            "summarizeBy": "none"
          },
          {
            "name": "Domain Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "736fd6d3-5e57-428f-988a-5db6563bcda0",
            "sourceColumn": "Domain Name",
            "summarizeBy": "none"
          },
          {
            "name": "Parent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "    'Customer Lookup'[TotalChildren] = 0,",
              "    \"No\",",
              "    \"Yes\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "a7c4f547-0cc8-4245-b091-e39d28272bf8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Customer Priority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "    AND('Customer Lookup'[Parent] = \"Yes\", 'Customer Lookup'[AnnualIncome] > 100000),",
              "    \"Priority\",",
              "    \"Standar\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "a520e919-d7cb-4068-b4a0-da5c70c35706",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Income Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    'Customer Lookup'[AnnualIncome] >= 150000, \"Very High\",",
              "    'Customer Lookup'[AnnualIncome] >= 100000, \"High\",",
              "    'Customer Lookup'[AnnualIncome] >= 50000, \"Average\",",
              "    \"Low\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "97520b32-e439-4900-b0de-95f935e4a0dc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Education Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    'Customer Lookup'[EducationLevel] in {\"High School\", \"Partial High School\"}, \"High School\",",
              "    OR('Customer Lookup'[EducationLevel] = \"Bachelors\", 'Customer Lookup'[EducationLevel] = \"Partial College\"), \"Udergrade\",",
              "    'Customer Lookup'[EducationLevel] = \"Graduate Degree\", \"Graduate\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "8ae743d8-3504-4aa9-ab17-209edacc8e5e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Customer Full Name (CC)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "'Customer Lookup'[Prefix] & \" \" & 'Customer Lookup'[FirstName] & \" \" & 'Customer Lookup'[LastName]"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "9f8bec85-d847-4ee6-b2d2-dcce04d7cce6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Birth Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "YEAR(",
              "    'Customer Lookup'[BirthDate]",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "e6e880cc-b323-47ac-bc44-b07c3e6be55f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "aafe2125-d6b6-4a27-9e4e-451da7c9b6b1",
        "partitions": [
          {
            "name": "Customer Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(Path&\"\\AdventureWorks Customer Lookup.csv\"),[Delimiter=\",\", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"CustomerKey\", Int64.Type}, {\"Prefix\", type text}, {\"FirstName\", type text}, {\"LastName\", type text}, {\"BirthDate\", type date}, {\"MaritalStatus\", type text}, {\"Gender\", type text}, {\"EmailAddress\", type text}, {\"AnnualIncome\", Int64.Type}, {\"TotalChildren\", Int64.Type}, {\"EducationLevel\", type text}, {\"Occupation\", type text}, {\"HomeOwner\", type text}}),",
                "    #\"Removed Errors\" = Table.RemoveRowsWithErrors(#\"Changed Type\", {\"CustomerKey\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Errors\", each [CustomerKey] <> null and [CustomerKey] <> \"\"),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Filtered Rows\",{{\"Prefix\", Text.Proper, type text}, {\"FirstName\", Text.Proper, type text}, {\"LastName\", Text.Proper, type text}}),",
                "    #\"Inserted Full Name Column\" = Table.AddColumn(#\"Capitalized Each Word\", \"Full Name\", each Text.Combine({[Prefix], [FirstName], [LastName]}, \" \"), type text),",
                "    #\"Duplicated Column Email Address\" = Table.DuplicateColumn(#\"Inserted Full Name Column\", \"EmailAddress\", \"Domain Name\"),",
                "    #\"Extracted Text Between Delimiters\" = Table.TransformColumns(#\"Duplicated Column Email Address\", {{\"Domain Name\", each Text.BetweenDelimiters(_, \"@\", \".\"), type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Extracted Text Between Delimiters\",\"-\",\" \",Replacer.ReplaceText,{\"Domain Name\"}),",
                "    #\"Capitalized Each Word Domain Name\" = Table.TransformColumns(#\"Replaced Value\",{{\"Domain Name\", Text.Proper, type text}})",
                "in",
                "    #\"Capitalized Each Word Domain Name\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calendar Lookup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isDefaultLabel": true,
            "lineageTag": "86e1d750-8f82-47f7-87c9-a1bf4e1df929",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Day Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e589453b-5b3b-409f-afd3-dc50389a5d42",
            "sourceColumn": "Day Name",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6f3ef15-8ee7-4095-aa84-37f7cfe18a3e",
            "sourceColumn": "Start of Week",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "f55b2132-7b3e-442a-b880-36dc88fbd1f1",
            "sourceColumn": "Start of Month",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "f14467fa-628a-400e-b83f-d4cd3c765432",
            "sourceColumn": "Start of Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fa2458c7-1e6e-44a2-8c2a-a665ac05613b",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "29353b0d-ca8d-455c-a3f3-3cf8a8140bec",
            "sourceColumn": "Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Start of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "9b5e5f0e-49f4-47dc-a6c1-8d7911361ffe",
            "sourceColumn": "Start of Year",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e8f1d4e8-e03a-4171-aac5-cccc1dd5f446",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Name (DAX)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    'Calendar Lookup'[Month],",
              "    1, \"January\",",
              "    2, \"Ferbuary\",",
              "    3, \"March\",",
              "    4, \"April\",",
              "    5, \"May\",",
              "    6, \"June\",",
              "    7, \"July\",",
              "    8, \"August\",",
              "    9, \"September\",",
              "    10, \"October\",",
              "    11, \"November\",",
              "    12, \"December\",",
              "    \"Others\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "cc3bff58-1fe1-4beb-8821-435595b20bb7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "UPPER(",
              "    LEFT(",
              "        'Calendar Lookup'[Month Name],",
              "        3",
              "    )",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "69a46fef-13c7-4187-bfe5-701486a0abc2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "WEEKDAY(",
              "    'Calendar Lookup'[Date],",
              "    2",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "c3430848-864b-44a7-a291-7504b1499372",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Weekend",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "    'Calendar Lookup'[Day of Week] in {6,7},",
              "    \"Weekend\",",
              "    \"Weekday\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "3c4d1ccb-f200-4556-98ea-16c837124117",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "levels": [
              {
                "name": "Start of Year",
                "column": "Start of Year",
                "lineageTag": "8065c075-bd71-4612-a2f8-52cb891c0507",
                "ordinal": 0
              },
              {
                "name": "Date",
                "column": "Date",
                "lineageTag": "0a336429-8c30-4419-b82a-35c23e63b67c",
                "ordinal": 3
              },
              {
                "name": "Start of Month",
                "column": "Start of Month",
                "lineageTag": "5b869aa8-4ef8-4919-b417-2bf1247b9c06",
                "ordinal": 1
              },
              {
                "name": "Start of Week",
                "column": "Start of Week",
                "lineageTag": "084c85c2-e3c8-4513-a247-1d44af02c07f",
                "ordinal": 2
              }
            ],
            "lineageTag": "6ef0e36a-c9e7-4849-ba4e-f78761e0fe93"
          }
        ],
        "lineageTag": "479d176b-ab5b-4d8b-b83f-b4d6bb004ac9",
        "partitions": [
          {
            "name": "Calendar Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(Path&\"\\AdventureWorks Calendar Lookup.csv\"),[Delimiter=\",\", Columns=1, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Date\", type date}}),",
                "    #\"Inserted Day Name\" = Table.AddColumn(#\"Changed Type\", \"Day Name\", each Date.DayOfWeekName([Date]), type text),",
                "    #\"Inserted Start of Week\" = Table.AddColumn(#\"Inserted Day Name\", \"Start of Week\", each Date.StartOfWeek([Date], Day.Monday)),",
                "    #\"Inserted Start of Month\" = Table.AddColumn(#\"Inserted Start of Week\", \"Start of Month\", each Date.StartOfMonth([Date]), type date),",
                "    #\"Inserted Start of Quarter\" = Table.AddColumn(#\"Inserted Start of Month\", \"Start of Quarter\", each Date.StartOfQuarter([Date]), type date),",
                "    #\"Inserted Month Name\" = Table.AddColumn(#\"Inserted Start of Quarter\", \"Month Name\", each Date.MonthName([Date]), type text),",
                "    #\"Inserted Month\" = Table.AddColumn(#\"Inserted Month Name\", \"Month\", each Date.Month([Date]), Int64.Type),",
                "    #\"Inserted Start of Year\" = Table.AddColumn(#\"Inserted Month\", \"Start of Year\", each Date.StartOfYear([Date]), type date),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Inserted Start of Year\", \"Year\", each Date.Year([Date]), Int64.Type)",
                "in",
                "    #\"Inserted Year\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sales Data",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "OrderDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isHidden": true,
            "lineageTag": "ad3a7965-21f8-4471-b766-2ea5ee7c6f8f",
            "sourceColumn": "OrderDate",
            "summarizeBy": "none"
          },
          {
            "name": "StockDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isHidden": true,
            "lineageTag": "8d7c1fba-37ac-4b65-a8d7-956a1a199e49",
            "sourceColumn": "StockDate",
            "summarizeBy": "none"
          },
          {
            "name": "OrderNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "48eac8c1-b746-4680-bf83-11ff30994f5b",
            "sourceColumn": "OrderNumber",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e1338d0d-f1f6-43e3-be0e-170edeab2f21",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "139a063e-e322-4d7d-aa62-366902ce3f5a",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "TerritoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f5bc4d1e-0193-49ba-9526-7790566ec213",
            "sourceColumn": "TerritoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "OrderLineItem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "499e5b93-4536-4678-bd6a-2ba99424f28e",
            "sourceColumn": "OrderLineItem",
            "summarizeBy": "sum"
          },
          {
            "name": "OrderQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c6e0cac5-c327-4802-9795-bb923ee73202",
            "sourceColumn": "OrderQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantity Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "    'Sales Data'[OrderQuantity] = 1,",
              "    \"Single Item\",",
              "    \"Multiple Item\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "a8c60aa4-e6b4-4746-91eb-05a00e8a1097",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "a05d9482-0548-4418-8490-c58846030fad",
        "partitions": [
          {
            "name": "Sales Data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(Path&\"\\Sales Data\"),",
                "    #\"Filtered Hidden Files1\" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform File\", each #\"Transform File\"([Content])),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File\"}),",
                "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File\", Table.ColumnNames(#\"Transform File\"(#\"Sample File\"))),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\",{{\"Source.Name\", type text}, {\"OrderDate\", type date}, {\"StockDate\", type date}, {\"OrderNumber\", type text}, {\"ProductKey\", Int64.Type}, {\"CustomerKey\", Int64.Type}, {\"TerritoryKey\", Int64.Type}, {\"OrderLineItem\", Int64.Type}, {\"OrderQuantity\", Int64.Type}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Source.Name\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Returns Data",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ReturnDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isHidden": true,
            "lineageTag": "3b24e933-3f04-48df-9655-ee37aab885b1",
            "sourceColumn": "ReturnDate",
            "summarizeBy": "none"
          },
          {
            "name": "TerritoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0ccea222-401c-44ec-960c-3c33f2126062",
            "sourceColumn": "TerritoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c446ecbd-0a78-443f-b943-e37f31772fa5",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "ReturnQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "acf6da34-ffa3-46d0-9efb-80645ba4107b",
            "sourceColumn": "ReturnQuantity",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "d0f53612-21eb-4840-8e5b-0cfe74caa71d",
        "partitions": [
          {
            "name": "Returns Data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(Path&\"\\AdventureWorks Returns Data.csv\"),[Delimiter=\",\", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ReturnDate\", type date}, {\"TerritoryKey\", Int64.Type}, {\"ProductKey\", Int64.Type}, {\"ReturnQuantity\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Measure Table",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "lineageTag": "ea2407e1-3e23-4f4b-a8e4-1f26867ba852",
        "measures": [
          {
            "name": "Quantity Sold",
            "expression": [
              "",
              "SUM(",
              "    'Sales Data'[OrderQuantity]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "a8e1713f-a9ec-46eb-bb23-5765c7d11a8e"
          },
          {
            "name": "Quantity Returned",
            "expression": [
              "",
              "SUM(",
              "    'Returns Data'[ReturnQuantity]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "2a54bbe6-43b0-477e-9d7f-60d56e1ec64b"
          },
          {
            "name": "Average Retail Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "AVERAGE(",
              "    'Product Lookup'[ProductPrice]",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "2d32f3e6-3418-4a29-91fd-eb6e9206f2f8"
          },
          {
            "name": "Total Returns",
            "expression": [
              "",
              "COUNT(",
              "    'Returns Data'[ReturnQuantity]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "5dad42e0-7361-4b59-8185-f5054c49c6a0"
          },
          {
            "name": "Total Orders",
            "expression": [
              "",
              "DISTINCTCOUNT(",
              "    'Sales Data'[OrderNumber]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "af05863d-ca1d-4a00-b67b-606d876a1b9a"
          },
          {
            "name": "Total Customers",
            "expression": [
              "",
              "DISTINCTCOUNT(",
              "    'Sales Data'[CustomerKey]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "96eb5c8f-b8f7-4a5e-b375-34dc315306be"
          },
          {
            "name": "Return Rate",
            "expression": [
              "",
              "DIVIDE(",
              "    [Quantity Returned],",
              "    [Quantity Sold],",
              "    \"No Sales\"",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "fe0837bc-bed5-457f-99a3-989cc54d1f29"
          },
          {
            "name": "Bulk Orders",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Orders],",
              "    'Sales Data'[OrderQuantity] > 1",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "c93b157e-81bd-4c5a-9b98-1eb58c4edeac"
          },
          {
            "name": "Weekend Orders",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Orders],",
              "    'Calendar Lookup'[Weekend] = \"Weekend\"",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "f3add8c3-b785-464e-95c4-44e6b5797e24"
          },
          {
            "name": "Bike Returns",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Returns],",
              "    'Product Categories Lookup'[CategoryName] = \"Bikes\"",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "6ab4019f-9144-454b-9564-c7609bed614b"
          },
          {
            "name": "Bike Sales",
            "expression": [
              "",
              "CALCULATE(",
              "    [Quantity Sold],",
              "    'Product Categories Lookup'[CategoryName] = \"Bikes\"",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "4ac8f554-1196-43ef-bc75-0ab90b41be5b"
          },
          {
            "name": "Bike Return Rate",
            "expression": [
              "",
              "DIVIDE(",
              "    [Bike Returns],",
              "    [Bike Sales]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "40c80bc9-d0cb-48ee-b6ca-54d1c6cf5e6c"
          },
          {
            "name": "All Orders",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Orders],",
              "    ALL(",
              "        'Sales Data'",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "3ce2e183-2bd5-4c84-85ad-13fa05896fee"
          },
          {
            "name": "% of All Orders",
            "expression": [
              "",
              "DIVIDE(",
              "    [Total Orders],",
              "    [All Orders],",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ebdaa280-d953-4a60-99c8-98870081d7a9"
          },
          {
            "name": "Overall Average Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [Average Retail Price],",
              "    ALL(",
              "        'Product Lookup'",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "120d627d-31e2-4059-9296-396a528c741e"
          },
          {
            "name": "All Returns",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Returns],",
              "    ALL(",
              "        'Returns Data'",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "07a1733f-5469-4913-a615-9b7de2b5c7ae"
          },
          {
            "name": "% of All Returns",
            "expression": [
              "",
              "DIVIDE(",
              "    [Total Returns],",
              "    [All Returns],",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "9a1872b8-38b1-49a7-85fb-49b0ff5752cd"
          },
          {
            "name": "High Ticket Orders",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Orders],",
              "    FILTER(",
              "        'Product Lookup',",
              "        'Product Lookup'[ProductPrice] > [Overall Average Price]",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "94e66f4e-c3ba-4cf0-afa8-8587f38651f5"
          },
          {
            "name": "Total Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "SUMX(",
              "    'Sales Data',",
              "    'Sales Data'[OrderQuantity] * RELATED('Product Lookup'[ProductPrice])",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "b9d51c5d-3981-495b-b477-fceb3d29e019"
          },
          {
            "name": "Average Revenue per Customer",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    [Total Revenue],",
              "    [Total Customers],",
              "    0",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "6dc3a02e-f042-4147-ab53-1031426ae1c7"
          },
          {
            "name": "Total Cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "SUMX(",
              "    'Sales Data',",
              "    'Sales Data'[OrderQuantity] * RELATED('Product Lookup'[ProductCost])",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "22bee898-c6b8-4d60-af0e-82f76f54b8d4"
          },
          {
            "name": "Total Profit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "[Total Revenue] - [Total Cost]"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "7190e05b-6027-4c74-a2e1-15483b9de861"
          },
          {
            "name": "YTD Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Revenue],",
              "    DATESYTD(",
              "        'Calendar Lookup'[Date]",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "adf42c34-81e1-451c-9df1-9779d77fafd4"
          },
          {
            "name": "Previous Month Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Revenue],",
              "    DATEADD(",
              "        'Calendar Lookup'[Date],",
              "        -1,",
              "        MONTH",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "b9fd157b-aaf9-4020-bfb4-c315fa66252b"
          },
          {
            "name": "Revenue Target",
            "expression": [
              "",
              "[Previous Month Revenue] * 1.1"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "216fa266-8c7e-4a8c-9d88-2d282d70d940"
          },
          {
            "name": "10-day Rolling Revenue",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Revenue],",
              "    DATESINPERIOD(",
              "        'Calendar Lookup'[Date],",
              "        MAX(",
              "            'Calendar Lookup'[Date]",
              "        ),",
              "        -10,",
              "        DAY",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "1c04d533-c44e-4f65-b40a-dd9c2e3fb828"
          },
          {
            "name": "Previous Month Returns",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Returns],",
              "    DATEADD(",
              "        'Calendar Lookup'[Date],",
              "        -1,",
              "        MONTH",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "47f27ccb-a29a-45b2-8048-4b5cae5436b7"
          },
          {
            "name": "Previous Month Orders",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Orders],",
              "    DATEADD(",
              "        'Calendar Lookup'[Date],",
              "        -1,",
              "        MONTH",
              "    )",
              ")"
            ],
            "lineageTag": "22297629-16f5-473a-9c87-6e9c7b115395"
          },
          {
            "name": "Previous Month Profit",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Profit],",
              "    DATEADD(",
              "        'Calendar Lookup'[Date],",
              "        -1,",
              "        MONTH",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "6c00a7e7-6558-46ef-ae51-23f7325243d8"
          },
          {
            "name": "Order Target",
            "expression": [
              "",
              "[Previous Month Orders] * 1.1"
            ],
            "formatString": "0",
            "lineageTag": "e998637e-6405-4b94-8026-e8d01ac0f520"
          },
          {
            "name": "Profit Target",
            "expression": [
              "",
              "[Previous Month Profit] * 1.1"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "69183be5-6da3-4d2b-a0c6-5583eb7b9b10"
          },
          {
            "name": "90-day Rolling Profit",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Profit],",
              "    DATESINPERIOD(",
              "        'Calendar Lookup'[Date],",
              "        MAX(",
              "            'Calendar Lookup'[Date]",
              "        ),",
              "        -90,",
              "        DAY",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "34aee440-ddc2-4a4f-81f8-4c8a87bc38a0"
          },
          {
            "name": "Max Dates",
            "expression": [
              "",
              "LASTDATE(",
              "    'Calendar Lookup'[Date]",
              ")"
            ],
            "formatString": "General Date",
            "lineageTag": "b816ceb8-7d37-48c4-b9f5-e472ace6e9a6"
          }
        ],
        "partitions": [
          {
            "name": "Measure Table",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}